"""Alembic environment, async flavour.

The stock template calls ``engine_from_config()``, which cannot drive asyncpg -
running it against this project's URL fails with "The asyncio extension
requires an async driver". The async recipe below comes from the Alembic
cookbook: build an AsyncEngine, then hand a sync-style connection to Alembic
through ``connection.run_sync``.
"""

from __future__ import annotations

import asyncio
from logging.config import fileConfig

# Registers the CREATE/ALTER TYPE autogeneration that vanilla Alembic lacks.
# Without it, adding a value to ReleaseStatus produces an empty migration.
import alembic_postgresql_enum
from alembic import context
from sqlalchemy import pool
from sqlalchemy.engine import Connection
from sqlalchemy.ext.asyncio import async_engine_from_config

from wascat.core.config import get_settings

# Importing this module registers every mapped class on Base.metadata. A
# missing import here makes autogenerate emit a DROP TABLE.
from wascat.models import Base

config = context.config

if config.config_file_name is not None:
    fileConfig(config.config_file_name)

settings = get_settings()
config.set_main_option("sqlalchemy.url", settings.database_url_str)

target_metadata = Base.metadata

#: Tables created by extensions, which autogenerate would otherwise try to drop.
EXTENSION_OWNED_TABLES = frozenset({"spatial_ref_sys"})


def include_object(obj: object, name: str | None, type_: str, *_: object) -> bool:
    """Keep extension-owned objects out of autogenerated migrations.

    pg_trgm and citext install their own operator classes and functions; left
    unfiltered, autogenerate proposes dropping them on every run.
    """
    return not (type_ == "table" and name in EXTENSION_OWNED_TABLES)


def _configure(connection: Connection) -> None:
    context.configure(
        connection=connection,
        target_metadata=target_metadata,
        # Catches a column whose Python type changed but whose name did not,
        # which is otherwise a silent no-op in autogenerate.
        compare_type=True,
        compare_server_default=True,
        include_object=include_object,
        render_as_batch=False,
        transaction_per_migration=True,
    )


def run_migrations_offline() -> None:
    context.configure(
        url=settings.sync_database_url,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
        compare_type=True,
    )
    with context.begin_transaction():
        context.run_migrations()


def _do_run_migrations(connection: Connection) -> None:
    _configure(connection)
    with context.begin_transaction():
        context.run_migrations()


async def run_migrations_online() -> None:
    section = config.get_section(config.config_ini_section, {})
    engine = async_engine_from_config(
        section,
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )
    async with engine.connect() as connection:
        await connection.run_sync(_do_run_migrations)
    await engine.dispose()


if context.is_offline_mode():
    run_migrations_offline()
else:
    asyncio.run(run_migrations_online())
