"""observed oktas and model class predictions

Two things the archive could not record before:

`image_records.observed_cloud_cover_oktas` - the total cloud cover a person
read off the sky, supplied in the observer's label table next to the cloud
genus. It is a new column rather than a second writer of `cloud_cover_oktas`,
which is derived from the segmentation mask and pinned to `cloud_fraction` by
the `okta_formula` check. Both are served; where they disagree, that is a fact
about the segmentation, not an error to reconcile away.

`prediction_models` + `image_class_predictions` - what a classifier said about
a frame, stored as the whole probability vector rather than a winning label. A
sky holds several genera at once, so one row per class is both the honest
shape and the queryable one. Nothing here runs inference: the archive records
model output the same way it records delivered masks.

Revision ID: 89aa875b8008
Revises: 4f2b8c7d1e05
Created: 2026-09-22 19:36:17.225127
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "89aa875b8008"
down_revision: str | None = "4f2b8c7d1e05"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "prediction_models",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("slug", sa.Text(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("version", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("trained_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("position", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("retired_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'", name=op.f("ck_prediction_models_model_slug_format")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_prediction_models")),
        sa.UniqueConstraint("slug", name=op.f("uq_prediction_models_slug")),
    )
    op.create_index(
        "ix_prediction_models_position", "prediction_models", ["position", "slug"], unique=False
    )
    op.create_table(
        "image_class_predictions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("image_id", sa.Text(), nullable=False),
        sa.Column("model_id", sa.UUID(), nullable=False),
        sa.Column("sky_class_id", sa.UUID(), nullable=True),
        sa.Column("sky_class_label", sa.Text(), nullable=False),
        sa.Column("probability", sa.Numeric(precision=6, scale=5), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "probability >= 0 AND probability <= 1",
            name=op.f("ck_image_class_predictions_probability_range"),
        ),
        sa.ForeignKeyConstraint(
            ["image_id"],
            ["image_records.id"],
            name=op.f("fk_image_class_predictions_image_id_image_records"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["model_id"],
            ["prediction_models.id"],
            name=op.f("fk_image_class_predictions_model_id_prediction_models"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["sky_class_id"],
            ["vocabulary_terms.id"],
            name=op.f("fk_image_class_predictions_sky_class_id_vocabulary_terms"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_image_class_predictions")),
        sa.UniqueConstraint("image_id", "model_id", "sky_class_label", name="uq_prediction_class"),
    )
    op.create_index(
        "ix_predictions_class_probability",
        "image_class_predictions",
        ["model_id", "sky_class_label", "probability"],
        unique=False,
    )
    op.create_index(
        "ix_predictions_image_model",
        "image_class_predictions",
        ["image_id", "model_id", "probability"],
        unique=False,
    )
    op.add_column(
        "image_records", sa.Column("observed_cloud_cover_oktas", sa.SmallInteger(), nullable=True)
    )
    op.create_check_constraint(
        op.f("ck_image_records_observed_okta_range"),
        "image_records",
        "observed_cloud_cover_oktas IS NULL OR observed_cloud_cover_oktas BETWEEN 0 AND 8",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("ck_image_records_observed_okta_range"), "image_records", type_="check")
    op.drop_column("image_records", "observed_cloud_cover_oktas")
    op.drop_index("ix_predictions_image_model", table_name="image_class_predictions")
    op.drop_index("ix_predictions_class_probability", table_name="image_class_predictions")
    op.drop_table("image_class_predictions")
    op.drop_index("ix_prediction_models_position", table_name="prediction_models")
    op.drop_table("prediction_models")
    # ### end Alembic commands ###
