"""catalog vocab iam audit ingest

Revision ID: 913452105ad1
Revises: db6e860d3c40
Created: 2026-09-02 23:19:45.488703
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "913452105ad1"
down_revision: str | None = "db6e860d3c40"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum(
        "SEASON", "TIME_OF_DAY", "LOCATION", "SKY_CLASS", "CONDITION_TAG", name="vocab_kind"
    ).create(op.get_bind())
    sa.Enum("QUEUED", "RUNNING", "SUCCEEDED", "FAILED", "INTERRUPTED", name="ingest_status").create(
        op.get_bind()
    )
    sa.Enum("DRAFT", "PUBLISHED", "RETIRED", name="release_status").create(op.get_bind())
    op.create_table(
        "collections",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("slug", sa.Text(), nullable=False),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("location_name", sa.Text(), nullable=True),
        sa.Column("latitude", sa.Numeric(precision=9, scale=6), nullable=True),
        sa.Column("longitude", sa.Numeric(precision=9, scale=6), nullable=True),
        sa.Column("instrument", sa.Text(), nullable=True),
        sa.Column("license", sa.Text(), nullable=True),
        sa.Column("citation", sa.Text(), nullable=True),
        sa.Column("doi", sa.Text(), nullable=True),
        sa.Column("methods_url", sa.Text(), nullable=True),
        sa.Column("publication_url", sa.Text(), nullable=True),
        sa.Column("position", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'", name=op.f("ck_collections_slug_format")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_collections")),
        sa.UniqueConstraint("slug", name=op.f("uq_collections_slug")),
    )
    op.create_index("ix_collections_position", "collections", ["position"], unique=False)
    op.create_table(
        "login_attempts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("email", postgresql.CITEXT(), nullable=False),
        sa.Column("ip", postgresql.INET(), nullable=True),
        sa.Column("successful", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_login_attempts")),
    )
    op.create_index(
        "ix_login_attempts_email_created", "login_attempts", ["email", "created_at"], unique=False
    )
    op.create_index(
        "ix_login_attempts_ip_created", "login_attempts", ["ip", "created_at"], unique=False
    )
    op.create_table(
        "permissions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("slug", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_permissions")),
        sa.UniqueConstraint("slug", name=op.f("uq_permissions_slug")),
    )
    op.create_table(
        "roles",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("slug", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("system", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_roles")),
        sa.UniqueConstraint("slug", name=op.f("uq_roles_slug")),
    )
    op.create_table(
        "sequence_references",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("video_id", sa.Text(), nullable=False),
        sa.Column("reference_frame_index", sa.Integer(), nullable=False),
        sa.Column("valid_circle_pixels", sa.Integer(), nullable=True),
        sa.Column(
            "registration_sample",
            sa.ARRAY(sa.Text()),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column(
            "mask_scale",
            sa.Numeric(precision=9, scale=6),
            server_default=sa.text("1"),
            nullable=False,
        ),
        sa.Column("corrected", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("cloud_outside_field_of_view", sa.Numeric(precision=9, scale=6), nullable=True),
        sa.Column("geometry", sa.Text(), nullable=True),
        sa.Column("frames", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "video_id ~ '^vid[0-9]+$'", name=op.f("ck_sequence_references_video_id_format")
        ),
        sa.CheckConstraint(
            "mask_scale >= 1", name=op.f("ck_sequence_references_mask_scale_at_least_one")
        ),
        sa.CheckConstraint(
            "reference_frame_index >= 0",
            name=op.f("ck_sequence_references_reference_frame_non_negative"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sequence_references")),
        sa.UniqueConstraint("video_id", name=op.f("uq_sequence_references_video_id")),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("email", postgresql.CITEXT(), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=False),
        sa.Column("full_name", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("position('@' in email) > 1", name=op.f("ck_users_email_shape")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("email", name=op.f("uq_users_email")),
    )
    op.create_table(
        "vocabulary_terms",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "kind",
            postgresql.ENUM(
                "SEASON",
                "TIME_OF_DAY",
                "LOCATION",
                "SKY_CLASS",
                "CONDITION_TAG",
                name="vocab_kind",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("slug", sa.Text(), nullable=False),
        sa.Column("label", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("position", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("system", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("merged_into_id", sa.UUID(), nullable=True),
        sa.Column("retired_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'", name=op.f("ck_vocabulary_terms_slug_format")
        ),
        sa.CheckConstraint(
            "NOT system OR retired_at IS NULL",
            name=op.f("ck_vocabulary_terms_system_terms_stay_active"),
        ),
        sa.CheckConstraint(
            "merged_into_id IS NULL OR merged_into_id <> id",
            name=op.f("ck_vocabulary_terms_no_self_merge"),
        ),
        sa.ForeignKeyConstraint(
            ["merged_into_id"],
            ["vocabulary_terms.id"],
            name=op.f("fk_vocabulary_terms_merged_into_id_vocabulary_terms"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_vocabulary_terms")),
        sa.UniqueConstraint("kind", "label", name=op.f("uq_vocabulary_terms_kind_label")),
        sa.UniqueConstraint("kind", "slug", name=op.f("uq_vocabulary_terms_kind_slug")),
    )
    op.create_index(
        "ix_vocabulary_terms_kind_active",
        "vocabulary_terms",
        ["kind"],
        unique=False,
        postgresql_where=sa.text("retired_at IS NULL"),
    )
    op.create_index(
        "ix_vocabulary_terms_kind_position", "vocabulary_terms", ["kind", "position"], unique=False
    )
    op.create_table(
        "audit_events",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("actor_user_id", sa.UUID(), nullable=True),
        sa.Column("actor_email", sa.Text(), nullable=True),
        sa.Column("action", sa.Text(), nullable=False),
        sa.Column("entity_type", sa.Text(), nullable=False),
        sa.Column("entity_id", sa.Text(), nullable=False),
        sa.Column("before", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("after", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("request_id", sa.Text(), nullable=True),
        sa.Column("ip", postgresql.INET(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["actor_user_id"],
            ["users.id"],
            name=op.f("fk_audit_events_actor_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_events")),
    )
    op.create_index(
        "ix_audit_events_action_created", "audit_events", ["action", "created_at"], unique=False
    )
    op.create_index(
        "ix_audit_events_actor_created",
        "audit_events",
        ["actor_user_id", "created_at"],
        unique=False,
    )
    op.create_index("ix_audit_events_created", "audit_events", ["created_at"], unique=False)
    op.create_index(
        "ix_audit_events_entity", "audit_events", ["entity_type", "entity_id"], unique=False
    )
    op.create_table(
        "refresh_sessions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("family_id", sa.UUID(), nullable=False),
        sa.Column("token_hash", sa.Text(), nullable=False),
        sa.Column(
            "issued_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("replaced_by_id", sa.UUID(), nullable=True),
        sa.Column("user_agent", sa.Text(), nullable=True),
        sa.Column("ip", postgresql.INET(), nullable=True),
        sa.ForeignKeyConstraint(
            ["replaced_by_id"],
            ["refresh_sessions.id"],
            name=op.f("fk_refresh_sessions_replaced_by_id_refresh_sessions"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_refresh_sessions_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_refresh_sessions")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_refresh_sessions_token_hash")),
    )
    op.create_index(
        "ix_refresh_sessions_active",
        "refresh_sessions",
        ["user_id"],
        unique=False,
        postgresql_where=sa.text("revoked_at IS NULL"),
    )
    op.create_index(
        "ix_refresh_sessions_family_id", "refresh_sessions", ["family_id"], unique=False
    )
    op.create_index("ix_refresh_sessions_user_id", "refresh_sessions", ["user_id"], unique=False)
    op.create_table(
        "releases",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("collection_id", sa.UUID(), nullable=False),
        sa.Column("version", sa.Text(), nullable=False),
        sa.Column(
            "status",
            postgresql.ENUM(
                "DRAFT", "PUBLISHED", "RETIRED", name="release_status", create_type=False
            ),
            server_default=sa.text("'DRAFT'"),
            nullable=False,
        ),
        sa.Column("current", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("retired_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("capture_start", sa.DateTime(timezone=True), nullable=True),
        sa.Column("capture_end", sa.DateTime(timezone=True), nullable=True),
        sa.Column("bundle_url", sa.Text(), nullable=True),
        sa.Column("bundle_checksum", sa.Text(), nullable=True),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "NOT current OR status = 'PUBLISHED'", name=op.f("ck_releases_current_is_published")
        ),
        sa.CheckConstraint(
            "status <> 'PUBLISHED' OR published_at IS NOT NULL",
            name=op.f("ck_releases_published_has_timestamp"),
        ),
        sa.CheckConstraint(
            "version ~ '^\\d+\\.\\d+(?:\\.\\d+)?$'", name=op.f("ck_releases_version_format")
        ),
        sa.ForeignKeyConstraint(
            ["collection_id"],
            ["collections.id"],
            name=op.f("fk_releases_collection_id_collections"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_releases")),
        sa.UniqueConstraint(
            "collection_id", "version", name=op.f("uq_releases_collection_id_version")
        ),
    )
    op.create_index(
        "ix_releases_collection_id_current", "releases", ["collection_id", "current"], unique=False
    )
    op.create_index(
        "uq_releases_collection_current",
        "releases",
        ["collection_id"],
        unique=True,
        postgresql_where=sa.text("current"),
    )
    op.create_table(
        "role_permissions",
        sa.Column("role_id", sa.UUID(), nullable=False),
        sa.Column("permission_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["permission_id"],
            ["permissions.id"],
            name=op.f("fk_role_permissions_permission_id_permissions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["roles.id"],
            name=op.f("fk_role_permissions_role_id_roles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("role_id", "permission_id", name=op.f("pk_role_permissions")),
    )
    op.create_table(
        "user_roles",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("role_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["role_id"], ["roles.id"], name=op.f("fk_user_roles_role_id_roles"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_user_roles_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("user_id", "role_id", name=op.f("pk_user_roles")),
    )
    op.create_table(
        "vocabulary_aliases",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("term_id", sa.UUID(), nullable=False),
        sa.Column(
            "kind",
            postgresql.ENUM(
                "SEASON",
                "TIME_OF_DAY",
                "LOCATION",
                "SKY_CLASS",
                "CONDITION_TAG",
                name="vocab_kind",
                create_type=False,
            ),
            nullable=False,
        ),
        sa.Column("value", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["term_id"],
            ["vocabulary_terms.id"],
            name=op.f("fk_vocabulary_aliases_term_id_vocabulary_terms"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_vocabulary_aliases")),
        sa.UniqueConstraint("kind", "value", name=op.f("uq_vocabulary_aliases_kind_value")),
    )
    op.create_index(
        "ix_vocabulary_aliases_term_id", "vocabulary_aliases", ["term_id"], unique=False
    )
    op.create_table(
        "image_records",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("release_id", sa.UUID(), nullable=False),
        sa.Column("collection_id", sa.UUID(), nullable=False),
        sa.Column("video_id", sa.Text(), nullable=False),
        sa.Column("video_number", sa.SmallInteger(), nullable=False),
        sa.Column("frame_index", sa.Integer(), nullable=False),
        sa.Column("cloud_fraction", sa.Numeric(precision=9, scale=6), nullable=True),
        sa.Column("cloud_cover_oktas", sa.SmallInteger(), nullable=True),
        sa.Column(
            "mask_scale",
            sa.Numeric(precision=9, scale=6),
            server_default=sa.text("1"),
            nullable=False,
        ),
        sa.Column("width", sa.Integer(), nullable=False),
        sa.Column("height", sa.Integer(), nullable=False),
        sa.Column("captured_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("latitude", sa.Numeric(precision=9, scale=6), nullable=True),
        sa.Column("longitude", sa.Numeric(precision=9, scale=6), nullable=True),
        sa.Column("instrument", sa.Text(), nullable=True),
        sa.Column("location_id", sa.UUID(), nullable=True),
        sa.Column("season_id", sa.UUID(), nullable=True),
        sa.Column("time_of_day_id", sa.UUID(), nullable=True),
        sa.Column("sky_class_id", sa.UUID(), nullable=True),
        sa.Column(
            "condition_tags", sa.ARRAY(sa.Text()), server_default=sa.text("'{}'"), nullable=False
        ),
        sa.Column("location_label", sa.Text(), nullable=True),
        sa.Column("season_label", sa.Text(), nullable=True),
        sa.Column("time_of_day_label", sa.Text(), nullable=True),
        sa.Column("sky_class_label", sa.Text(), nullable=True),
        sa.Column(
            "provenance",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column("custom", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("has_source", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("has_mask", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("sort_key", sa.Text(collation="C"), nullable=False),
        sa.Column("search_text", sa.Text(), server_default=sa.text("''"), nullable=False),
        sa.Column(
            "search_tsv",
            postgresql.TSVECTOR(),
            sa.Computed("to_tsvector('simple', search_text)", persisted=True),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("retired_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("id ~ '^WAS-[A-Z0-9-]+$'", name=op.f("ck_image_records_id_format")),
        sa.CheckConstraint(
            "video_id ~ '^vid[0-9]+$'", name=op.f("ck_image_records_video_id_format")
        ),
        sa.CheckConstraint(
            "(cloud_fraction IS NULL) = (cloud_cover_oktas IS NULL)",
            name=op.f("ck_image_records_measurement_pairing"),
        ),
        sa.CheckConstraint(
            "cloud_cover_oktas IS NULL OR cloud_cover_oktas = least(8, greatest(0, round(cloud_fraction * 8)::int))",
            name=op.f("ck_image_records_okta_formula"),
        ),
        sa.CheckConstraint(
            "frame_index >= 0", name=op.f("ck_image_records_frame_index_non_negative")
        ),
        sa.CheckConstraint(
            "mask_scale >= 1", name=op.f("ck_image_records_mask_scale_at_least_one")
        ),
        sa.CheckConstraint(
            "width > 0 AND height > 0", name=op.f("ck_image_records_positive_dimensions")
        ),
        sa.ForeignKeyConstraint(
            ["collection_id"],
            ["collections.id"],
            name=op.f("fk_image_records_collection_id_collections"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["location_id"],
            ["vocabulary_terms.id"],
            name=op.f("fk_image_records_location_id_vocabulary_terms"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["release_id"],
            ["releases.id"],
            name=op.f("fk_image_records_release_id_releases"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["season_id"],
            ["vocabulary_terms.id"],
            name=op.f("fk_image_records_season_id_vocabulary_terms"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["sky_class_id"],
            ["vocabulary_terms.id"],
            name=op.f("fk_image_records_sky_class_id_vocabulary_terms"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["time_of_day_id"],
            ["vocabulary_terms.id"],
            name=op.f("fk_image_records_time_of_day_id_vocabulary_terms"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_image_records")),
    )
    op.create_index(
        "ix_image_records_captured_sort",
        "image_records",
        ["captured_at", "sort_key", "id"],
        unique=False,
        postgresql_where=sa.text("captured_at IS NOT NULL"),
    )
    op.create_index(
        "ix_image_records_collection_sort",
        "image_records",
        ["collection_id", "sort_key", "id"],
        unique=False,
    )
    op.create_index(
        "ix_image_records_frame", "image_records", ["video_id", "frame_index"], unique=True
    )
    op.create_index("ix_image_records_location", "image_records", ["location_id"], unique=False)
    op.create_index(
        "ix_image_records_oktas_sort",
        "image_records",
        ["cloud_cover_oktas", "sort_key", "id"],
        unique=False,
        postgresql_where=sa.text("cloud_cover_oktas IS NOT NULL"),
    )
    op.create_index(
        "ix_image_records_release_sort",
        "image_records",
        ["release_id", "sort_key", "id"],
        unique=False,
    )
    op.create_index(
        "ix_image_records_search_trgm",
        "image_records",
        [sa.literal_column("search_text gin_trgm_ops")],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(
        "ix_image_records_search_tsv",
        "image_records",
        ["search_tsv"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(
        "ix_image_records_segmented_sort",
        "image_records",
        ["has_mask", "sort_key", "id"],
        unique=False,
    )
    op.create_index("ix_image_records_sort", "image_records", ["sort_key", "id"], unique=False)
    op.create_index(
        "ix_image_records_tags",
        "image_records",
        ["condition_tags"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(
        "ix_image_records_taxonomy",
        "image_records",
        ["sky_class_id", "season_id", "time_of_day_id"],
        unique=False,
    )
    op.create_index(
        "ix_image_records_video_sort", "image_records", ["video_id", "sort_key", "id"], unique=False
    )
    op.create_table(
        "ingest_runs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column(
            "status",
            postgresql.ENUM(
                "QUEUED",
                "RUNNING",
                "SUCCEEDED",
                "FAILED",
                "INTERRUPTED",
                name="ingest_status",
                create_type=False,
            ),
            server_default=sa.text("'QUEUED'"),
            nullable=False,
        ),
        sa.Column("release_id", sa.UUID(), nullable=True),
        sa.Column("requested_by_id", sa.UUID(), nullable=True),
        sa.Column(
            "params",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column(
            "stats",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'"),
            nullable=False,
        ),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("records_total", sa.Integer(), nullable=True),
        sa.Column("records_done", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["release_id"],
            ["releases.id"],
            name=op.f("fk_ingest_runs_release_id_releases"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["requested_by_id"],
            ["users.id"],
            name=op.f("fk_ingest_runs_requested_by_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ingest_runs")),
    )
    op.create_index(
        "ix_ingest_runs_status_created", "ingest_runs", ["status", "created_at"], unique=False
    )
    op.create_table(
        "artifacts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("image_id", sa.Text(), nullable=False),
        sa.Column("type", sa.Text(), nullable=False),
        sa.Column("media_type", sa.Text(), nullable=False),
        sa.Column("object_key", sa.Text(), nullable=False),
        sa.Column("checksum", sa.Text(), nullable=False),
        sa.Column("bytes", sa.BigInteger(), nullable=False),
        sa.Column("width", sa.Integer(), nullable=True),
        sa.Column("height", sa.Integer(), nullable=True),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "checksum ~ '^[a-f0-9]{64}$'", name=op.f("ck_artifacts_checksum_sha256")
        ),
        sa.CheckConstraint(
            "type IN ('source', 'mask', 'thumbnail', 'webp')", name=op.f("ck_artifacts_known_type")
        ),
        sa.CheckConstraint("bytes > 0", name=op.f("ck_artifacts_bytes_positive")),
        sa.ForeignKeyConstraint(
            ["image_id"],
            ["image_records.id"],
            name=op.f("fk_artifacts_image_id_image_records"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_artifacts")),
        sa.UniqueConstraint("image_id", "type", name=op.f("uq_artifacts_image_id_type")),
        sa.UniqueConstraint("object_key", name=op.f("uq_artifacts_object_key")),
    )
    op.create_index("ix_artifacts_image_id", "artifacts", ["image_id"], unique=False)
    op.create_index("ix_artifacts_type", "artifacts", ["type"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_artifacts_type", table_name="artifacts")
    op.drop_index("ix_artifacts_image_id", table_name="artifacts")
    op.drop_table("artifacts")
    op.drop_index("ix_ingest_runs_status_created", table_name="ingest_runs")
    op.drop_table("ingest_runs")
    op.drop_index("ix_image_records_video_sort", table_name="image_records")
    op.drop_index("ix_image_records_taxonomy", table_name="image_records")
    op.drop_index("ix_image_records_tags", table_name="image_records", postgresql_using="gin")
    op.drop_index("ix_image_records_sort", table_name="image_records")
    op.drop_index("ix_image_records_segmented_sort", table_name="image_records")
    op.drop_index("ix_image_records_search_tsv", table_name="image_records", postgresql_using="gin")
    op.drop_index(
        "ix_image_records_search_trgm", table_name="image_records", postgresql_using="gin"
    )
    op.drop_index("ix_image_records_release_sort", table_name="image_records")
    op.drop_index(
        "ix_image_records_oktas_sort",
        table_name="image_records",
        postgresql_where=sa.text("cloud_cover_oktas IS NOT NULL"),
    )
    op.drop_index("ix_image_records_location", table_name="image_records")
    op.drop_index("ix_image_records_frame", table_name="image_records")
    op.drop_index("ix_image_records_collection_sort", table_name="image_records")
    op.drop_index(
        "ix_image_records_captured_sort",
        table_name="image_records",
        postgresql_where=sa.text("captured_at IS NOT NULL"),
    )
    op.drop_table("image_records")
    op.drop_index("ix_vocabulary_aliases_term_id", table_name="vocabulary_aliases")
    op.drop_table("vocabulary_aliases")
    op.drop_table("user_roles")
    op.drop_table("role_permissions")
    op.drop_index(
        "uq_releases_collection_current", table_name="releases", postgresql_where=sa.text("current")
    )
    op.drop_index("ix_releases_collection_id_current", table_name="releases")
    op.drop_table("releases")
    op.drop_index("ix_refresh_sessions_user_id", table_name="refresh_sessions")
    op.drop_index("ix_refresh_sessions_family_id", table_name="refresh_sessions")
    op.drop_index(
        "ix_refresh_sessions_active",
        table_name="refresh_sessions",
        postgresql_where=sa.text("revoked_at IS NULL"),
    )
    op.drop_table("refresh_sessions")
    op.drop_index("ix_audit_events_entity", table_name="audit_events")
    op.drop_index("ix_audit_events_created", table_name="audit_events")
    op.drop_index("ix_audit_events_actor_created", table_name="audit_events")
    op.drop_index("ix_audit_events_action_created", table_name="audit_events")
    op.drop_table("audit_events")
    op.drop_index("ix_vocabulary_terms_kind_position", table_name="vocabulary_terms")
    op.drop_index(
        "ix_vocabulary_terms_kind_active",
        table_name="vocabulary_terms",
        postgresql_where=sa.text("retired_at IS NULL"),
    )
    op.drop_table("vocabulary_terms")
    op.drop_table("users")
    op.drop_table("sequence_references")
    op.drop_table("roles")
    op.drop_table("permissions")
    op.drop_index("ix_login_attempts_ip_created", table_name="login_attempts")
    op.drop_index("ix_login_attempts_email_created", table_name="login_attempts")
    op.drop_table("login_attempts")
    op.drop_index("ix_collections_position", table_name="collections")
    op.drop_table("collections")
    sa.Enum("DRAFT", "PUBLISHED", "RETIRED", name="release_status").drop(op.get_bind())
    sa.Enum("QUEUED", "RUNNING", "SUCCEEDED", "FAILED", "INTERRUPTED", name="ingest_status").drop(
        op.get_bind()
    )
    sa.Enum(
        "SEASON", "TIME_OF_DAY", "LOCATION", "SKY_CLASS", "CONDITION_TAG", name="vocab_kind"
    ).drop(op.get_bind())
    # ### end Alembic commands ###
