"""What the dashboard may send when managing people.

Two things are deliberately *not* here.

There is no password field on either schema. Passwords are generated by the
server and shown once, the same way ``wascat users create`` does it, so an
administrator never types a password on someone else's behalf and no password
ever travels up from a browser form.

There is no delete schema. An account is disabled, never removed: audit events
name their actor, and deleting the row would leave the archive's own history
pointing at nobody.
"""

from __future__ import annotations

from typing import Annotated

from pydantic import BaseModel, ConfigDict, Field

#: Deliberately not ``EmailStr``, matching ``Credentials`` in auth_router. The
#: address is a sign-in identifier rather than a destination - nothing is ever
#: sent to it - and EmailStr enforces deliverability, which rejects the reserved
#: domains real deployments use internally (admin@wascat.local, .internal).
SignInAddress = Annotated[
    str,
    Field(min_length=3, max_length=320, pattern=r"^[^@\s]+@[^@\s]+$"),
]

#: A role is named by slug. The set is seeded and closed - admin, curator,
#: viewer - and the router checks membership against the database rather than
#: trusting this, so an unknown slug is a 404 and not a silently ignored field.
RoleSlug = Annotated[str, Field(pattern=r"^[a-z][a-z0-9-]{1,30}$")]


class UserCreate(BaseModel):
    """Invite someone. The generated password comes back once in the response."""

    model_config = ConfigDict(extra="forbid", populate_by_name=True)

    email: SignInAddress
    full_name: str | None = Field(default=None, alias="fullName", max_length=200)
    # One role, not a list. Every seeded role is a superset of the one below it,
    # so combining them expresses nothing that a single choice cannot, and a
    # multi-select would invite assignments nobody can reason about.
    role: RoleSlug


class UserUpdate(BaseModel):
    """Change a name, a role, or whether the account may sign in.

    Every field is optional and the router reads ``exclude_unset``, so omitting
    a field leaves it alone rather than clearing it.
    """

    model_config = ConfigDict(extra="forbid", populate_by_name=True)

    full_name: str | None = Field(default=None, alias="fullName", max_length=200)
    role: RoleSlug | None = None
    is_active: bool | None = Field(default=None, alias="isActive")
